version: '3.8'

services:

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    env_file:
      - ./.env
    volumes:
      - logs_data:/app/session_logs

  redis_service:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  logs_data:
  redis_data: