version: '3.8'

services:

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    env_file:
      - ./.env

  redis_service:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379